
[ClassVersion("1.0.0.0"), FriendlyName("xNetBIOS")]
class MSFT_xNetBIOS : OMI_BaseResource
{
    [Key, Description("Specifies the alias of a network interface.")] String InterfaceAlias;
    [Required, Description("Specifies if NetBIOS should be enabled or disabled or obtained from the DHCP server (Default). If static IP, Enable NetBIOS."), ValueMap{"Default","Enable","Disable"}, Values{"Default","Enable","Disable"}] String Setting;
};
