[ClassVersion("1.0.0.0"), FriendlyName("xIPAddressOption")]
class MSFT_xIPAddressOption : OMI_BaseResource
{
    [Key, Description("The target IP address, must already be configured on the system.")] string IPAddress;
    [Write, Description("Skip as source option of the ip address.")] boolean SkipAsSource;
};
