[ClassVersion("1.0"), FriendlyName("xHostsFile")] 
class MSFT_xHostsFile : OMI_BaseResource
{
  [Key] string hostName;
  [Key] string ipAddress;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
