[ClassVersion("1.0.0.0"), FriendlyName("NetAdapterAdvancedProperty")]
class MSFT_NetAdapterAdvancedProperty : OMI_BaseResource
{
    [Key, Description("Specifies the registry keyword of the property that should be in desired state.")] String RegistryKeyword;
    [Key, Description("Specifies the network adapter name.")] String NetworkAdapterName;
    [Required, Description("Specifies the registry value.")] String RegistryValue;
    [Read, Description("Output Display value of selected RegistryKeyword.")] String DisplayValue;
};
