[ClassVersion("1.0.0.0"), FriendlyName("NetAdapterLso")]
class DSC_NetAdapterLso : OMI_BaseResource
{
    [Key, Description("Specifies the name of network adapter.")] String Name;
    [Write, Description("This switch will causes hidden network adapters to be included in the search.")] Boolean IncludeHidden;
    [Key, Description("Specifies which protocol to make changes to."), ValueMap{"V1IPv4","IPv4","IPv6"}, Values{"V1IPv4","IPv4","IPv6"}] String Protocol;
    [Required, Description("Specifies whether LSO should be enabled or disabled.")] Boolean State;
};
